trying to make sure workflows work

diff --git a/.github/workflows/loadspeed.yml b/.github/workflows/loadspeed.yml
--- a/.github/workflows/loadspeed.yml
+++ b/.github/workflows/loadspeed.yml
@@ -1,11 +1,11 @@
-name:  Run loadspeed playwright tests
+name:  Run Responsive playwright tests
 
 on:
   push:
   pull_request:
 
 jobs:
-  build-test-loadspeed:
+  build-test-metatags:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -19,4 +19,30 @@ jobs:
       - name: Install playwright browsers
         run: npx playwright install --with-deps
       - name: Run tests
-        run: npx playwright test  tests/loadSpeed.spec.js
+        env:
+          PLAYWRIGHT_CLI_EXIT_ON_FIRST_FAILURE: '1'
+        run: npx playwright test tests/loadSpeed.spec.js --config=playwright.config.js || echo "tests_failed=true" >> $GITHUB_ENV
+
+      - name: Print tests_failed
+        run: echo "tests_failed=$tests_failed"
+  
+
+      - name: Install jq
+        run: sudo apt-get install jq
+
+     
+      - name: Archive Lighthouse report, videos, and screenshots
+        if: env.tests_failed == 'true'
+        uses: actions/upload-artifact@v2
+        with:
+          name: test-artifacts
+          path: |
+            lighthouse-report.json
+            test-results/
+            **/*.mp4
+            **/*.png
+      - name: Exit with failure if tests failed
+        if: env.tests_failed == 'true'
+        run: exit 1
+
+   
diff --git a/.github/workflows/metatags.yml b/.github/workflows/metatags.yml
--- a/.github/workflows/metatags.yml
+++ b/.github/workflows/metatags.yml
@@ -19,14 +19,20 @@ jobs:
       - name: Install playwright browsers
         run: npx playwright install --with-deps
       - name: Run tests
-        run: npx playwright test tests/metaTags.spec.js --config=playwright.config.js || exit 0
+        env:
+          PLAYWRIGHT_CLI_EXIT_ON_FIRST_FAILURE: '1'
+        run: npx playwright test tests/metaTags.spec.js --config=playwright.config.js || echo "tests_failed=true" >> $GITHUB_ENV
 
+      - name: Print tests_failed
+        run: echo "tests_failed=$tests_failed"
   
 
       - name: Install jq
         run: sudo apt-get install jq
 
+     
       - name: Archive Lighthouse report, videos, and screenshots
+        if: env.tests_failed == 'true'
         uses: actions/upload-artifact@v2
         with:
           name: test-artifacts
@@ -35,3 +41,6 @@ jobs:
             test-results/
             **/*.mp4
             **/*.png
+      - name: Exit with failure if tests failed
+        if: env.tests_failed == 'true'
+        run: exit 1
diff --git a/.github/workflows/privacymodal.yml b/.github/workflows/privacymodal.yml
--- a/.github/workflows/privacymodal.yml
+++ b/.github/workflows/privacymodal.yml
@@ -1,11 +1,11 @@
-name:  Run Responsive playwright tests
+name:  Run privacy modal playwright tests
 
 on:
   push:
   pull_request:
 
 jobs:
-  build-test-metatags:
+  build-test-privacymodal:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -21,7 +21,7 @@ jobs:
       - name: Run tests
         env:
           PLAYWRIGHT_CLI_EXIT_ON_FIRST_FAILURE: '1'
-        run: npx playwright test tests/responsive.spec.js --config=playwright.config.js || echo "tests_failed=true" >> $GITHUB_ENV
+        run: npx playwright test tests/privacyModal.spec.js --config=playwright.config.js || echo "tests_failed=true" >> $GITHUB_ENV
 
       - name: Print tests_failed
         run: echo "tests_failed=$tests_failed"
@@ -44,5 +44,3 @@ jobs:
       - name: Exit with failure if tests failed
         if: env.tests_failed == 'true'
         run: exit 1
-
-   
