Update test.yml
should cause exit 1 correctly at end of workflow file

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -33,7 +33,7 @@ jobs:
       - name: Run tests
         env:
           PLAYWRIGHT_CLI_EXIT_ON_FIRST_FAILURE: '1'
-        run: xvfb-run --auto-servernum --server-args='-screen 0 1280x1024x24' npx playwright test tests/lighthouse.test.js || (echo "tests_failed=true" >> $GITHUB_ENV && exit 1)
+        run: xvfb-run --auto-servernum --server-args='-screen 0 1280x1024x24' npx playwright test tests/lighthouse.test.js || echo "tests_failed=true" >> $GITHUB_ENV
 
       - name: Print tests_failed
         run: echo "tests_failed=$tests_failed"
@@ -51,3 +51,7 @@ jobs:
             test-results/
             **/*.mp4
             **/*.png
+
+      - name: Exit with failure if tests failed
+        if: env.tests_failed == 'true'
+        run: exit 1
